"""initial schema

Revision ID: 7f7ae826645b
Revises: 
Create Date: 2026-09-01 22:10:00.904020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f7ae826645b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_rollup',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('domain_name', sa.String(length=253), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('pass_count', sa.BigInteger(), nullable=False),
    sa.Column('fail_known', sa.BigInteger(), nullable=False),
    sa.Column('fail_unclassified', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('volume >= 0 AND pass_count >= 0 AND fail_known >= 0 AND fail_unclassified >= 0', name='ck_daily_rollup_counts_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name', 'date', name='uq_daily_rollup_domain_date')
    )
    op.create_index(op.f('ix_daily_rollup_date'), 'daily_rollup', ['date'], unique=False)
    op.create_index(op.f('ix_daily_rollup_domain_name'), 'daily_rollup', ['domain_name'], unique=False)
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=253), nullable=False),
    sa.Column('role', sa.Enum('primary', 'transactional', 'marketing', 'billing', 'regional', 'parked', 'tenant', name='role', native_enum=False), nullable=False),
    sa.Column('dmarc', sa.Enum('reject', 'quarantine', 'none', 'missing', 'na', name='dmarc_posture', native_enum=False), nullable=False),
    sa.Column('spf', sa.Enum('pass', 'softfail', 'missing', 'na', name='spf_posture', native_enum=False), nullable=False),
    sa.Column('dkim', sa.Enum('pass', 'partial', 'missing', 'na', name='dkim_posture', native_enum=False), nullable=False),
    sa.Column('mtasts', sa.Enum('enforce', 'testing', 'missing', 'na', name='mtasts_posture', native_enum=False), nullable=False),
    sa.Column('tlsrpt', sa.Enum('present', 'missing', 'na', name='tlsrpt_posture', native_enum=False), nullable=False),
    sa.Column('rua_matches', sa.Boolean(), nullable=True),
    sa.Column('rua_value', sa.Text(), nullable=True),
    sa.Column('dns_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(dmarc IN ('missing', 'na') AND rua_matches IS NULL) OR (dmarc NOT IN ('missing', 'na') AND rua_matches IS NOT NULL)", name='ck_domain_rua_matches_requires_dmarc'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_name'), 'domain', ['name'], unique=True)
    op.create_index('ix_domain_rua_mismatch', 'domain', ['rua_matches'], unique=False, postgresql_where='rua_matches IS FALSE')
    op.create_table('ingest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('success', 'partial', 'failure', name='ingest_outcome', native_enum=False), nullable=False),
    sa.Column('messages_seen', sa.Integer(), nullable=False),
    sa.Column('reports_parsed', sa.Integer(), nullable=False),
    sa.Column('reports_failed', sa.Integer(), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.CheckConstraint('messages_seen >= 0 AND reports_parsed >= 0 AND reports_failed >= 0', name='ck_ingest_run_counts_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_run_started_at'), 'ingest_run', ['started_at'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=512), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_email', sa.String(length=320), nullable=True),
    sa.Column('date_begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_message_id', sa.String(length=512), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_org_name'), 'report', ['org_name'], unique=False)
    op.create_index(op.f('ix_report_report_id'), 'report', ['report_id'], unique=True)
    op.create_index(op.f('ix_report_source_message_id'), 'report', ['source_message_id'], unique=False)
    op.create_table('setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('classification', sa.Enum('known', 'unclassified', name='source_class', native_enum=False), nullable=False),
    sa.Column('ip_ranges', postgresql.ARRAY(postgresql.INET()), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_classification'), 'source', ['classification'], unique=False)
    op.create_index(op.f('ix_source_org_name'), 'source', ['org_name'], unique=True)
    op.create_table('tls_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=512), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('date_begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_message_id', sa.String(length=512), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tls_report_org_name'), 'tls_report', ['org_name'], unique=False)
    op.create_index(op.f('ix_tls_report_report_id'), 'tls_report', ['report_id'], unique=True)
    op.create_index(op.f('ix_tls_report_source_message_id'), 'tls_report', ['source_message_id'], unique=False)
    op.create_table('report_row',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('report_pk', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=253), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('source_org', sa.String(length=255), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.Column('disposition', sa.Enum('none', 'quarantine', 'reject', name='disposition', native_enum=False), nullable=False),
    sa.Column('spf_aligned', sa.Boolean(), nullable=False),
    sa.Column('dkim_aligned', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.CheckConstraint('count >= 0', name='ck_report_row_count_non_negative'),
    sa.ForeignKeyConstraint(['report_pk'], ['report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_row_date'), 'report_row', ['date'], unique=False)
    op.create_index('ix_report_row_domain_date', 'report_row', ['domain_name', 'date'], unique=False)
    op.create_index(op.f('ix_report_row_domain_name'), 'report_row', ['domain_name'], unique=False)
    op.create_index(op.f('ix_report_row_report_pk'), 'report_row', ['report_pk'], unique=False)
    op.create_index(op.f('ix_report_row_source_ip'), 'report_row', ['source_ip'], unique=False)
    op.create_table('tls_result_row',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tls_report_pk', sa.Integer(), nullable=False),
    sa.Column('policy_domain', sa.String(length=253), nullable=False),
    sa.Column('policy_mode', sa.Enum('enforce', 'testing', 'none', name='policy_mode', native_enum=False), nullable=False),
    sa.Column('result_type', sa.String(length=128), nullable=False),
    sa.Column('success_count', sa.BigInteger(), nullable=False),
    sa.Column('failure_count', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.CheckConstraint('success_count >= 0 AND failure_count >= 0', name='ck_tls_result_row_counts_non_negative'),
    sa.ForeignKeyConstraint(['tls_report_pk'], ['tls_report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tls_result_row_date'), 'tls_result_row', ['date'], unique=False)
    op.create_index('ix_tls_result_row_domain_date', 'tls_result_row', ['policy_domain', 'date'], unique=False)
    op.create_index(op.f('ix_tls_result_row_policy_domain'), 'tls_result_row', ['policy_domain'], unique=False)
    op.create_index(op.f('ix_tls_result_row_result_type'), 'tls_result_row', ['result_type'], unique=False)
    op.create_index(op.f('ix_tls_result_row_tls_report_pk'), 'tls_result_row', ['tls_report_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tls_result_row_tls_report_pk'), table_name='tls_result_row')
    op.drop_index(op.f('ix_tls_result_row_result_type'), table_name='tls_result_row')
    op.drop_index(op.f('ix_tls_result_row_policy_domain'), table_name='tls_result_row')
    op.drop_index('ix_tls_result_row_domain_date', table_name='tls_result_row')
    op.drop_index(op.f('ix_tls_result_row_date'), table_name='tls_result_row')
    op.drop_table('tls_result_row')
    op.drop_index(op.f('ix_report_row_source_ip'), table_name='report_row')
    op.drop_index(op.f('ix_report_row_report_pk'), table_name='report_row')
    op.drop_index(op.f('ix_report_row_domain_name'), table_name='report_row')
    op.drop_index('ix_report_row_domain_date', table_name='report_row')
    op.drop_index(op.f('ix_report_row_date'), table_name='report_row')
    op.drop_table('report_row')
    op.drop_index(op.f('ix_tls_report_source_message_id'), table_name='tls_report')
    op.drop_index(op.f('ix_tls_report_report_id'), table_name='tls_report')
    op.drop_index(op.f('ix_tls_report_org_name'), table_name='tls_report')
    op.drop_table('tls_report')
    op.drop_index(op.f('ix_source_org_name'), table_name='source')
    op.drop_index(op.f('ix_source_classification'), table_name='source')
    op.drop_table('source')
    op.drop_table('setting')
    op.drop_index(op.f('ix_report_source_message_id'), table_name='report')
    op.drop_index(op.f('ix_report_report_id'), table_name='report')
    op.drop_index(op.f('ix_report_org_name'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_ingest_run_started_at'), table_name='ingest_run')
    op.drop_table('ingest_run')
    op.drop_index('ix_domain_rua_mismatch', table_name='domain', postgresql_where='rua_matches IS FALSE')
    op.drop_index(op.f('ix_domain_name'), table_name='domain')
    op.drop_table('domain')
    op.drop_index(op.f('ix_daily_rollup_domain_name'), table_name='daily_rollup')
    op.drop_index(op.f('ix_daily_rollup_date'), table_name='daily_rollup')
    op.drop_table('daily_rollup')
    # ### end Alembic commands ###
